Code/POS_WEB/POS_WEB/Controllers/ExcelWorkbookController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Threading.Tasks;
using CentricKernel;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using POS_WEB.AppContext;
using POS_WEB.Models.Services.ExcelFile;
using POS_WEB.Models.Services.ImportMotocycle;
using POS_WEB.Models.Services.Inventory;

namespace POS_WEB.Controllers
{
 
    public class ExcelWorkbookController : Controller
    {
        private readonly DataContext _context;
        private readonly WorkbookContext _workbook;
        private readonly IHostingEnvironment _rootDir;
        public ExcelWorkbookController(DataContext context, IHostingEnvironment env) {
            _context = context;
            _rootDir = env;
            _workbook = new WorkbookContext();
        }
        public IActionResult Import()
        {
            ViewBag.style = "fa fa-cubes";
            ViewBag.Main = "Inventory";
            ViewBag.Page = "Item Master Data ";
            ViewBag.Subpage = "Import";
            ViewBag.InventoryMenu = "show";
            ViewBag.ItemMasterData = "highlight";
            return View();
        }

        public IActionResult PreviewComponent() {
            var group_defined_uom = from duom in _context.GroupDUoMs.OrderBy(g=>g.GroupUoMID)
                                    join uom in _context.UnitofMeasures on duom.AltUOM equals uom.ID
                                    join guom in _context.GroupUOMs.Where(w=>w.Delete==false) on duom.GroupUoMID equals guom.ID
                                    select new
                                    {
                                        duom.ID,
                                        duom.GroupUoMID,
                                        duom.AltUOM,                                       
                                        uom.Name,
                                        duom.Factor
                                    };
            var itemMaster = new {
                PriceLists = _context.PriceLists.Where(w => w.Delete == false),
                GroupUOMs = _context.GroupUOMs.Where(w => w.Delete == false),
                GroupDefinedUoM = group_defined_uom,
                PrinterNames = _context.PrinterNames.Where(w => w.Delete == false),
                Warehouses = _context.Warehouses.Where(w=>w.Delete==false),
                ItemGroup1 = _context.ItemGroup1.Where(ig1 => ig1.Delete==false && string.Compare(ig1.Name, "None", true) != 0).OrderBy(g1 => g1.ItemG1ID),
                ItemGroup2 = _context.ItemGroup2.Where(ig2 =>ig2.Delete==false && string.Compare(ig2.Name, "None", true) != 0).OrderBy(g2 => g2.ItemG1ID),
                ItemGroup3 = _context.ItemGroup3.Where(ig3 =>ig3.Delete==false && string.Compare(ig3.Name, "None", true) != 0).OrderBy(g3 => g3.ItemG1ID).OrderBy(g3 => g3.ItemG2ID)
            };
            return Ok(itemMaster);
        }


        [HttpPost]
        public IActionResult GetFileNames()
        {
            ModelMessage message = new ModelMessage(ModelState);
            IList<string> sheetNames = new List<string>();
            if (Request.Form.Files.Count > 0)
            {
                IFormFile file = Request.Form.Files[0];
                if (ModelState.IsValid)
                {
                    using (Stream fs = new MemoryStream())
                    {
                        file.CopyTo(fs);
                        fs.Position = 0;                       
                        IWorkbook wb = WorkbookFactory.Create(fs);
                        for (int i = 0; i < wb.NumberOfSheets; i++)
                        {
                            sheetNames.Add(wb.GetSheetAt(i).SheetName);
                        }
                    }
                }
            }

            return Ok(sheetNames);
        }

        public async Task<IActionResult> Download()
        {
            string fullPath = Path.GetFullPath(string.Format("{0}{1}", _rootDir.WebRootPath, "/FileTemplate/template.xlsx"));

            var memory = new MemoryStream();
            using (Stream fs = System.IO.File.OpenRead(fullPath))
            {
                await fs.CopyToAsync(memory);
                memory.Position = 0;
                return File(memory, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", Path.GetFileName(fullPath));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ExportItemMasters(FileDirectory directory)
        {
            ModelMessage message = new ModelMessage(ModelState);
            RNGCryptoServiceProvider rng = new RNGCryptoServiceProvider();
            byte[] randomBytes = new byte[12];
            rng.GetBytes(randomBytes);
            string ext = ".xlsx, .xls";
            string fileName = directory.FileName ?? Convert.ToBase64String(randomBytes);
            if (!string.IsNullOrEmpty(fileName))
            {
                fileName = fileName.Contains(ext.Split(".")[1]) ? fileName : fileName + directory.FileType;
            }

            //if (!Directory.Exists(directory.FilePath))
            //{
            //    ModelState.AddModelError("directory.FilePath", "File Path is not valid.");
            //}
            string fullPath = string.Format(@"{0}\{1}", _rootDir.WebRootPath, fileName);

            //if (ModelState.IsValid)
            //{
            //    var appointments = GetMotocycleTimelyAppointments();
            //    _workbook.SaveAsExcel(appointments, fullPath);
            //    message.Add("valiation.Success", "File has been save successfully.");
            //    message.Action = ModelAction.CONFIRM;

            //}

            return Ok(message.Bind(ModelState));
        }

        [HttpPost]
        public IActionResult PreviewItemMasterData()
        {
            IFormFile file = Request.Form.Files[0];
            using (Stream fs = new MemoryStream())
            {
                int sheetIndex = int.Parse(Request.Form["SheetIndex"]);
                file.CopyToAsync(fs);
                fs.Position = 0;
                IWorkbook wb = _workbook.ReadWorkbook(fs);
                return Ok(_workbook.ParseKeyValue(wb.GetSheetAt(sheetIndex)));
            }
        }

    }
}

Code/POS_WEB/POS_WEB/Views/ExcelWorkbook/Import.cshtml
@model POS_WEB.Models.Services.ExcelFile.ExcelFormFile;
<style>
    .wrap-table {
        width: 100%;
    }

    table tr th:first-child, table tr td:first-child {
        width: 20px;
    }
    .block .wrap-table {
        min-height: 150px;
    }
</style>
<script src="~/js/ExcelFile/import-item-master.js" defer></script>
@*<h1>@Localizer["Import Item Master"]</h1>*@
<div class="my1" ck-message-summary></div>
<ul id="nav-import-list" class="nav nav-tabs">
    <li id="tab-new-upload" class="active"><i class="fas fa-plus-circle fa-lg fn-sky"></i> @Localizer["Upload"]</li>
    <li id="tab-preview"><i class="fas fa-search fa-lg fn-sky"></i> @Localizer["Table Reference"]</li>
</ul>

<div class="block" id="tab-content-customer">
    <div id="content-new-upload">
        <div class="wrap-block col-three">
            <div class="left-block">
                <div class="block border">
                    <div class="title">@Localizer["Upload File"]</div>
                    <form id="item-master-formfile" class="mt-2" method="post" enctype="multipart/form-data">
                        <div class="ck-file-container">
                            <img src="~/Images//file.jpg" />
                            <input asp-for="FormFile" type="file" accept=".xls, .xlsx" />
                            <select id="filename-list" name="SheetIndex" class="form-control" disabled></select>
                        </div>
                        <span asp-validation-for="FormFile" class="text-danger"></span>
                        <button asp-action="Download" asp-controller="ExcelWorkbook" class="btn btn-primary mt-2"><i class="far fa-file-excel"></i> @Localizer["Template"]</button>
                        <button id="preview-item-master-data" class="btn btn-primary mt-2" type="button" disabled><i class="fas fa-search"></i> @Localizer["Preview"]</button>
                        <button id="submit-item-master-data" class="btn btn-primary mt-2" type="button" disabled><i class="fas fa-file-upload"></i> @Localizer["Upload"]</button>
                    </form>
                    <form style="text-align: left;" hidden>
                        @Html.AntiForgeryToken()
                        <div model-validation-success></div>
                        <label class="form-label">@Localizer["File Type"] <span class="fn-red">*</span></label>
                        <select class="form-control" name="FileType">
                            <option value=".xlsx">XLSX (Excel 2007 / Higher)</option>
                            <option value=".xls">XLS (Excel 2003 / Lower)</option>
                        </select>

                        <label class="form-label">@Localizer["File Name"]</label>
                        <input class="form-control" name="FileName" />
                    </form>
                </div>
            </div>
            <div class="right-block fuse">
                <div model-validation-for="itemMasterData.Barcode"></div>
            </div>
        </div>

        <div class="wrap-table list myt1" style="min-height:400px;">
            @{ int index = 0; }
            <table id="preview-item-master-data-list">
                <tr>
                    <th>@Localizer["No."]</th>
                    <th>@Localizer["Code"]</th>
                    <th>@Localizer["Khmer Name"]</th>
                    <th>@Localizer["English Name"]</th>
                    <th>@Localizer["Cost"]</th>
                    <th>@Localizer["Unit Price"]</th>
                    <th>@Localizer["PriceListID"]</th>
                    <th>@Localizer["GroupUomID"]</th>
                    <th>@Localizer["InventoryUoMID"]</th>
                    <th>@Localizer["SaleUomID"]</th>
                    <th>@Localizer["PurchaseUomID"]</th>
                    <th>@Localizer["WarehouseID"]</th>
                    <th>@Localizer["Type"]</th>
                    <th>@Localizer["ItemGroup1ID"]</th>
                    <th>@Localizer["ItemGroup2ID"]</th>
                    <th>@Localizer["ItemGroup3ID"]</th>
                    <th>@Localizer["Inventory"]</th>
                    <th>@Localizer["Sale"]</th>
                    <th>@Localizer["Purchase"]</th>
                    <th>@Localizer["Barcode"]</th>
                    <th>@Localizer["PrintToID"]</th>
                    <th>@Localizer["Image"]</th>
                    <th>@Localizer["Process"]</th>
                </tr>

            </table>
            <div id="preview-loader" class="ck-ajaxloader">
                <img src="~/Images//ajaxloader/timefilter.gif" />
            </div>
        </div>
    </div>

    <div id="content-item-master-data" hidden>
        @*<div class="flexbox flex-end">
                <div class="group-search-boxes">
                    <div id="text-search" class="wrap-search-box">
                        <div class="wrap-input show">
                            <i id="i-search-motocycle" class="i-search fas fa-search"></i>
                            <input id="search-uploaded-motocycles" class="ignore" type="text" placeholder="Search uploaded files ...">
                            <i id="i-close" class="i-close far fa-times-circle"></i>
                        </div>
                        <div class="btn-search" style="display: none;"><i class="fas fa-search"></i></div>
                    </div>
                </div>
            </div>*@
        <div class="wrap-table list">
            <div class="wrap-block col-two">
                <div class="left-block">
                    <div class="block">
                        <div class="title">@Localizer["Price List"]</div>
                        <div class="wrap-table">
                            <table id="im-table-pricelist">
                                <tr>
                                    <th>@Localizer["PriceListID"]</th>
                                    <th>@Localizer["Name"]</th>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="right-block">
                    <div class="block">
                        <div class="title">@Localizer["Warehouse"]</div>
                        <div class="wrap-table">
                            <table id="im-table-warehouse">
                                <tr>
                                    <th>@Localizer["WarehouseID"]</th>
                                    <th>@Localizer["BranchID"]</th>
                                    <th>@Localizer["Code"]</th>
                                    <th>@Localizer["Name"]</th>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div><hr />
                <div class="wrap-block col-two">
                    <div class="left-block">
                        <div class="block">
                            <div class="title">@Localizer["Group UoM"]</div>
                            <div class="wrap-table">
                                <table id="im-table-group-uom">
                                    <tr>
                                        <th>@Localizer["GroupUoMID"]</th>
                                        <th>@Localizer["Code"]</th>
                                        <th>@Localizer["Name"]</th>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="right-block">
                        <div class="block">
                            <div class="title">@Localizer["Group Defined UoM"]</div>
                            <div class="wrap-table">
                                <table id="im-table-group-defined-uom">
                                    <tr>
                                        <th>@Localizer["GroupUoMID"]</th>
                                        <th>@Localizer["AltUOM"]</th>
                                        <th>@Localizer["Name"]</th>
                                        <th>@Localizer["Factor"]</th>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div><hr />
            <div class="wrap-block col-three myt1">
                <div class="left-block">
                    <div class="block">
                        <div class="title">@Localizer["Item Group 1"]</div>
                        <div class="wrap-table">
                            <table id="im-table-item-group1">
                                <tr>
                                    <th>@Localizer["ItemG1ID"]</th>
                                    <th>@Localizer["Name"]</th>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="middle-block">
                    <div class="block">
                        <div class="title">@Localizer["Item Group 2"]</div>
                        <div class="wrap-table">
                            <table id="im-table-item-group2">
                                <tr>
                                    <th>@Localizer["ItemG2ID"]</th>
                                    <th>@Localizer["Name"]</th>
                                    <th>@Localizer["ItemG1ID"]</th>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="right-block">
                    <div class="block">
                        <div class="title">@Localizer["Item Group 3"]</div>
                        <div class="wrap-table">
                            <table id="im-table-item-group3">
                                <tr>
                                    <th>@Localizer["ItemG3ID"]</th>
                                    <th>@Localizer["Name"]</th>
                                    <th>@Localizer["ItemG1ID"]</th>
                                    <th>@Localizer["ItemG2ID"]</th>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div><hr />
     
            <div class="wrap-block col-two">
                <div class="left-block">
                    <div class="block">
                        <div class="title">@Localizer["Printer"]</div>
                        <div class="wrap-table">
                            <table id="im-table-printer">
                                <tr>
                                    <th>@Localizer["PrintToID"]</th>
                                    <th>@Localizer["Name"]</th>
                                </tr>
                            </table>
                        </div>

                    </div>

                </div>
                
            </div>
        </div>
    </div>
</div>